// API Error Codes
export const ERROR_CODES = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_EXISTS: 'AUTH_EMAIL_EXISTS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_INACTIVE: 'USER_INACTIVE',

  // Lounge
  LOUNGE_NOT_FOUND: 'LOUNGE_NOT_FOUND',
  LOUNGE_SLUG_EXISTS: 'LOUNGE_SLUG_EXISTS',
  LOUNGE_CREATE_LIMIT: 'LOUNGE_CREATE_LIMIT',
  LOUNGE_NOT_MEMBER: 'LOUNGE_NOT_MEMBER',
  LOUNGE_ALREADY_MEMBER: 'LOUNGE_ALREADY_MEMBER',

  // Post
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  POST_NOT_AUTHOR: 'POST_NOT_AUTHOR',

  // Comment
  COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',
  COMMENT_NOT_AUTHOR: 'COMMENT_NOT_AUTHOR',

  // Permission
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  NOT_MANAGER: 'NOT_MANAGER',
  NOT_OWNER: 'NOT_OWNER',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Server
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

// Limits
export const LIMITS = {
  MAX_LOUNGES_PER_USER: 2,
  MAX_MEDIA_PER_POST: 10,
  MAX_TAGS_PER_POST: 10,
  MAX_FILE_SIZE_IMAGE: 10 * 1024 * 1024, // 10MB
  MAX_FILE_SIZE_VIDEO: 100 * 1024 * 1024, // 100MB
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
} as const;

// Token Expiry
export const TOKEN_EXPIRY = {
  ACCESS_TOKEN: 15 * 60, // 15 minutes in seconds
  REFRESH_TOKEN: 7 * 24 * 60 * 60, // 7 days in seconds
} as const;

// Cache TTL
export const CACHE_TTL = {
  LOUNGE_INFO: 5 * 60, // 5 minutes
  POPULAR_POSTS: 1 * 60, // 1 minute
  USER_SESSION: 7 * 24 * 60 * 60, // 7 days
  VIEW_COUNT_DEBOUNCE: 24 * 60 * 60, // 24 hours
} as const;
